from colorama import Fore
from termcolor import colored

create_login = Fore.GREEN + 'Create your login: '
create_pass = Fore.GREEN + 'Create your password: '
login_exist = Fore.GREEN + 'This login already exist, try something else'
enter = Fore.GREEN + 'Great, now you must enter in your account'
write_login = Fore.GREEN + 'Write your login: '
write_pass = Fore.GREEN + 'Write your password: '
welcome = Fore.GREEN + 'Welcome to ATM, '
incorrect_log_pass = Fore.GREEN + 'Login or password is incorrect '
count_deposit = Fore.GREEN + 'Specify the amount you want to deposit: '
naebchik = Fore.GREEN + 'Mne kajetsa ti naebchik'
deposited = Fore.GREEN + 'Money has been deposited'
not_number = Fore.GREEN + 'You enter not number, please try again'
withdraw_count = Fore.GREEN + 'Specify the amount you want to withdraw: '
not_enough_funds = Fore.GREEN + 'There are not enough funds in your account'
success_withdraw = Fore.GREEN + 'You have successfully withdrawn funds'
options = Fore.GREEN + 'Choose option: \n'
option1 = Fore.GREEN + 'Press "1" to view balance \n'
option2 = Fore.GREEN + 'Press "2" to enter deposit \n'
option3 = Fore.GREEN + 'Press "3" to withdraw \n'
option4 = Fore.GREEN + 'Press "4" to exit from your account \n'
option5 = Fore.GREEN + 'Press "5" to create new account \n'
option6 = Fore.GREEN + 'Press "6" to exit'
incorrect_number = Fore.GREEN + 'Incorrect number, you must choose 1, 2, 3, 4, 5 or 6'
registration = Fore.GREEN + ' Press "1" to registration\n'
authorisation = Fore.GREEN + 'Press "2" to authorisation'
first_create_acc = Fore.GREEN + 'First, you need to create account'
incorrect_numbers12 = Fore.GREEN + 'Incorrect number, you must choose 1 or 2'

